layout:
  color: dark  # Options: light, dark
  logo: logo.png  # Logo image file name
  title: "Nostr Articles"  # Site title

blog_url: https://blog.nostrize.me

relays:
  - wss://relay.damus.io
  - wss://nostr.wine
  - wss://relay.nostr.band
  - wss://nos.lol
  - wss://relay.primal.net

features:
  comments: true
  nostr_links: njump.me
  tag_discovery: true

# todo: implement settings
settings:
  tag_discovery:
    fetch_count_per_tag: 100      # fetch this many events per tag
    popular_articles_count: 10    # max number of articles to display in tag discovery

articles:
  - naddr1qvzqqqr4gupzqmnyhq7p7e60kq997xvpds5hkeq5hanlq9vffczd6nr9062pqthgqq25x6r2d90hzaj529f9gur2x9h4yt2gfy69qm05rzu
  - naddr1qvzqqqr4gupzqmnyhq7p7e60kq997xvpds5hkeq5hanlq9vffczd6nr9062pqthgqq2j6ezsgu69j7n92cmxxmfsgyeyyvjtxfuk7lwjq6s
  - naddr1qvzqqqr4gupzqmnyhq7p7e60kq997xvpds5hkeq5hanlq9vffczd6nr9062pqthgqq24wmjfwp6rv6t8v935ujfhv4yr2wzzdfz5gl5quve
  - naddr1qvzqqqr4gupzqwlsccluhy6xxsr6l9a9uhhxf75g85g8a709tprjcn4e42h053vaqqyrzwrxvc6ngvfkxty9t8
  - naddr1qq2k2vph23v9y7rcvf8n27292avhv6rrve54sqgkwaehxw309aex2mrp0yh8qunfd4skctnwv46qz9nhwden5te0wfjkccte9ehx7um5wghxyctwvsq3camnwvaz7tmwdaehgu3wvf5hgcm0d9hx2u3wwdhkx6tpdsq3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7qg0waehxw309ahx7um5wghx6mmdqgsxue9c8s0kwnaspf03nqtv99akg99lvlcptz2wqnw5cet7jsgza6qrqsqqqa28d4u2lk

profiles: # add nprofiles here
  - nprofile1qqsrhuxx8l9ex335q7he0f09aej04zpazpl0ne2cgukyawd24mayt8gpp4mhxue69uhkummn9ekx7mqprhgw8
  - nprofile1qqsxue9c8s0kwnaspf03nqtv99akg99lvlcptz2wqnw5cet7jsgza6qpp4mhxue69uhkummn9ekx7mq8k7c9l